apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container 
      tail_files: true
      enabled: true
      paths:
        - /var/log/containers/game-hall-*.log
        - /var/log/containers/game-records-*.log
        - /var/log/containers/gamecontroller*.log
        - /var/log/containers/gameservice-*.log
        - /var/log/containers/scheduler*.log
        - /var/log/containers/node*.log
        - /var/log/containers/transfer*.log
      processors:
        - add_tags: 
            tags: [uat]
            target: "environment"
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
              - logs_path: 
                  logs_path: "/var/log/containers/"
        - drop_event:
            when:
              regexp:
                 message: "GoogleHC"
    output.logstash:
      hosts: ['logstash-logstash.monitoring.svc.cluster.local:5044']
      enabled: true
#    output.elasticsearch:
#      hosts: ["http://10.209.19.4:9200"]
