apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-harbor
        namespace: flux-system
      version: "v0.15.0"
  interval: 1m
  install:
    remediation:
      retries: 3
